### ISSUE TITLE
Doesn't work with Ren'Py v7.4.0.1028

### ISSUE THREAD

**Issue by kyouryuukunn** [Enerccio/librpydb#1]
This doesn't work correctly with Ren'Py v7.4.0.1028.
I tested windows 10 & ubuntu.20.04.1

This is error code.

Resetting cache.
Resetting cache.
Resetting cache.
Exception in thread DAP:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "debugger.py", line 55, in run
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by kyouryuukunn** [comment]
Sorry, I moved to https://github.com/Enerccio/renpy-debugger/issues/2
